"""Core module - Foundation components with no internal dependencies.

This module provides the basic building blocks used throughout the application:
- Version information
- Custom exceptions
- Configuration dataclasses
- Constants and defaults
- Console colors and formatting utilities
"""

from cja_auto_sdr.core.colors import (
    ANSIColors,
    ConsoleColors,
    _format_error_msg,
    format_file_size,
    open_file_in_default_app,
)
from cja_auto_sdr.core.config import (
    APITuningConfig,
    CacheConfig,
    CircuitBreakerConfig,
    CircuitState,
    LogConfig,
    RetryConfig,
    SDRConfig,
    WizardConfig,
    WorkerConfig,
)
from cja_auto_sdr.core.constants import (
    AUTO_WORKERS_SENTINEL,
    CONFIG_SCHEMA,
    CREDENTIAL_FIELDS,
    DEFAULT_API_FETCH_WORKERS,
    DEFAULT_BATCH_WORKERS,
    DEFAULT_CACHE,
    DEFAULT_CACHE_SIZE,
    DEFAULT_CACHE_TTL,
    DEFAULT_LOG,
    DEFAULT_RETRY,
    DEFAULT_RETRY_CONFIG,
    DEFAULT_VALIDATION_WORKERS,
    DEFAULT_WORKERS,
    ENV_VAR_MAPPING,
    EXTENSION_TO_FORMAT,
    FORMAT_ALIASES,
    JWT_DEPRECATED_FIELDS,
    LOG_FILE_BACKUP_COUNT,
    LOG_FILE_MAX_BYTES,
    MAX_BATCH_WORKERS,
    RETRYABLE_STATUS_CODES,
    VALIDATION_SCHEMA,
    _get_credential_fields,
    auto_detect_workers,
    infer_format_from_path,
    should_generate_format,
)
from cja_auto_sdr.core.exceptions import (
    APIError,
    CircuitBreakerOpen,
    CJASDRError,
    ConcurrentOrgReportError,
    ConfigurationError,
    CredentialSourceError,
    MemoryLimitExceeded,
    OutputError,
    ProfileConfigError,
    ProfileError,
    ProfileNotFoundError,
    RetryableHTTPError,
    ValidationError,
)
from cja_auto_sdr.core.version import __version__

__all__ = [
    "AUTO_WORKERS_SENTINEL",
    "CONFIG_SCHEMA",
    "CREDENTIAL_FIELDS",
    "DEFAULT_API_FETCH_WORKERS",
    "DEFAULT_BATCH_WORKERS",
    "DEFAULT_CACHE",
    "DEFAULT_CACHE_SIZE",
    "DEFAULT_CACHE_TTL",
    "DEFAULT_LOG",
    "DEFAULT_RETRY",
    "DEFAULT_RETRY_CONFIG",
    "DEFAULT_VALIDATION_WORKERS",
    "DEFAULT_WORKERS",
    "ENV_VAR_MAPPING",
    "EXTENSION_TO_FORMAT",
    # Constants
    "FORMAT_ALIASES",
    "JWT_DEPRECATED_FIELDS",
    "LOG_FILE_BACKUP_COUNT",
    "LOG_FILE_MAX_BYTES",
    "MAX_BATCH_WORKERS",
    "RETRYABLE_STATUS_CODES",
    "VALIDATION_SCHEMA",
    "ANSIColors",
    "APIError",
    "APITuningConfig",
    # Exceptions
    "CJASDRError",
    "CacheConfig",
    "CircuitBreakerConfig",
    "CircuitBreakerOpen",
    "CircuitState",
    "ConcurrentOrgReportError",
    # Config validation + credentials
    "ConfigValidator",
    "ConfigurationError",
    # Colors
    "ConsoleColors",
    "CredentialLoader",
    "CredentialResolver",
    "CredentialSourceError",
    "DotenvCredentialLoader",
    "EnvironmentCredentialLoader",
    # Logging + performance
    "JSONFormatter",
    "JsonFileCredentialLoader",
    "LogConfig",
    "MemoryLimitExceeded",
    "OutputError",
    "PerformanceTracker",
    "ProfileConfigError",
    "ProfileError",
    "ProfileNotFoundError",
    # Config dataclasses
    "RetryConfig",
    "RetryableHTTPError",
    "SDRConfig",
    "ValidationError",
    "WizardConfig",
    "WorkerConfig",
    # Version
    "__version__",
    "_format_error_msg",
    "_get_credential_fields",
    # Profiles
    "add_profile_interactive",
    "auto_detect_workers",
    "filter_credentials",
    "format_file_size",
    "get_cja_home",
    "get_profile_path",
    "get_profiles_dir",
    "infer_format_from_path",
    "list_profiles",
    "load_credentials_from_env",
    "load_profile_credentials",
    "normalize_credential_value",
    "open_file_in_default_app",
    "resolve_active_profile",
    "setup_logging",
    "should_generate_format",
    "show_profile",
    "test_profile",
    "validate_config_file",
    "validate_credentials",
    "validate_env_credentials",
    "validate_profile_name",
]


from cja_auto_sdr.core.lazy import make_getattr

__getattr__ = make_getattr(
    __name__,
    [
        "JSONFormatter",
        "setup_logging",
        "PerformanceTracker",
        "ConfigValidator",
        "validate_config_file",
        "validate_credentials",
        "CredentialLoader",
        "CredentialResolver",
        "DotenvCredentialLoader",
        "EnvironmentCredentialLoader",
        "JsonFileCredentialLoader",
        "filter_credentials",
        "load_credentials_from_env",
        "normalize_credential_value",
        "validate_env_credentials",
        "add_profile_interactive",
        "get_cja_home",
        "get_profile_path",
        "get_profiles_dir",
        "list_profiles",
        "load_profile_credentials",
        "resolve_active_profile",
        "show_profile",
        "test_profile",
        "validate_profile_name",
    ],
    mapping={
        "JSONFormatter": "cja_auto_sdr.core.logging",
        "setup_logging": "cja_auto_sdr.core.logging",
        "PerformanceTracker": "cja_auto_sdr.core.perf",
        "ConfigValidator": "cja_auto_sdr.core.config_validation",
        "validate_config_file": "cja_auto_sdr.core.config_validation",
        "validate_credentials": "cja_auto_sdr.core.config_validation",
        "CredentialLoader": "cja_auto_sdr.core.credentials",
        "CredentialResolver": "cja_auto_sdr.core.credentials",
        "DotenvCredentialLoader": "cja_auto_sdr.core.credentials",
        "EnvironmentCredentialLoader": "cja_auto_sdr.core.credentials",
        "JsonFileCredentialLoader": "cja_auto_sdr.core.credentials",
        "filter_credentials": "cja_auto_sdr.core.credentials",
        "load_credentials_from_env": "cja_auto_sdr.core.credentials",
        "normalize_credential_value": "cja_auto_sdr.core.credentials",
        "validate_env_credentials": "cja_auto_sdr.core.credentials",
        "add_profile_interactive": "cja_auto_sdr.core.profiles",
        "get_cja_home": "cja_auto_sdr.core.profiles",
        "get_profile_path": "cja_auto_sdr.core.profiles",
        "get_profiles_dir": "cja_auto_sdr.core.profiles",
        "list_profiles": "cja_auto_sdr.core.profiles",
        "load_profile_credentials": "cja_auto_sdr.core.profiles",
        "resolve_active_profile": "cja_auto_sdr.core.profiles",
        "show_profile": "cja_auto_sdr.core.profiles",
        "test_profile": "cja_auto_sdr.core.profiles",
        "validate_profile_name": "cja_auto_sdr.core.profiles",
    },
)
