"""Core module - Foundation components with no internal dependencies.

This module provides the basic building blocks used throughout the application:
- Version information
- Custom exceptions
- Configuration dataclasses
- Constants and defaults
- Console colors and formatting utilities
"""

from cja_auto_sdr.core.version import __version__

from cja_auto_sdr.core.exceptions import (
    CJASDRError,
    ConfigurationError,
    APIError,
    ValidationError,
    OutputError,
    ProfileError,
    ProfileNotFoundError,
    ProfileConfigError,
    CredentialSourceError,
    CircuitBreakerOpen,
    RetryableHTTPError,
    ConcurrentOrgReportError,
    MemoryLimitExceeded,
)

from cja_auto_sdr.core.config import (
    RetryConfig,
    CacheConfig,
    LogConfig,
    WorkerConfig,
    APITuningConfig,
    CircuitState,
    CircuitBreakerConfig,
    SDRConfig,
    WizardConfig,
)

from cja_auto_sdr.core.constants import (
    FORMAT_ALIASES,
    EXTENSION_TO_FORMAT,
    DEFAULT_API_FETCH_WORKERS,
    DEFAULT_VALIDATION_WORKERS,
    DEFAULT_BATCH_WORKERS,
    MAX_BATCH_WORKERS,
    AUTO_WORKERS_SENTINEL,
    DEFAULT_CACHE_SIZE,
    DEFAULT_CACHE_TTL,
    LOG_FILE_MAX_BYTES,
    LOG_FILE_BACKUP_COUNT,
    DEFAULT_RETRY,
    DEFAULT_CACHE,
    DEFAULT_LOG,
    DEFAULT_WORKERS,
    DEFAULT_RETRY_CONFIG,
    VALIDATION_SCHEMA,
    RETRYABLE_STATUS_CODES,
    CONFIG_SCHEMA,
    JWT_DEPRECATED_FIELDS,
    ENV_VAR_MAPPING,
    CREDENTIAL_FIELDS,
    auto_detect_workers,
    infer_format_from_path,
    should_generate_format,
    _get_credential_fields,
)

from cja_auto_sdr.core.colors import (
    ConsoleColors,
    ANSIColors,
    format_file_size,
    open_file_in_default_app,
    _format_error_msg,
)

__all__ = [
    # Version
    '__version__',
    # Exceptions
    'CJASDRError',
    'ConfigurationError',
    'APIError',
    'ValidationError',
    'OutputError',
    'ProfileError',
    'ProfileNotFoundError',
    'ProfileConfigError',
    'CredentialSourceError',
    'CircuitBreakerOpen',
    'RetryableHTTPError',
    'ConcurrentOrgReportError',
    'MemoryLimitExceeded',
    # Config dataclasses
    'RetryConfig',
    'CacheConfig',
    'LogConfig',
    'WorkerConfig',
    'APITuningConfig',
    'CircuitState',
    'CircuitBreakerConfig',
    'SDRConfig',
    'WizardConfig',
    # Constants
    'FORMAT_ALIASES',
    'EXTENSION_TO_FORMAT',
    'DEFAULT_API_FETCH_WORKERS',
    'DEFAULT_VALIDATION_WORKERS',
    'DEFAULT_BATCH_WORKERS',
    'MAX_BATCH_WORKERS',
    'AUTO_WORKERS_SENTINEL',
    'DEFAULT_CACHE_SIZE',
    'DEFAULT_CACHE_TTL',
    'LOG_FILE_MAX_BYTES',
    'LOG_FILE_BACKUP_COUNT',
    'DEFAULT_RETRY',
    'DEFAULT_CACHE',
    'DEFAULT_LOG',
    'DEFAULT_WORKERS',
    'DEFAULT_RETRY_CONFIG',
    'VALIDATION_SCHEMA',
    'RETRYABLE_STATUS_CODES',
    'CONFIG_SCHEMA',
    'JWT_DEPRECATED_FIELDS',
    'ENV_VAR_MAPPING',
    'CREDENTIAL_FIELDS',
    'auto_detect_workers',
    'infer_format_from_path',
    'should_generate_format',
    '_get_credential_fields',
    # Colors
    'ConsoleColors',
    'ANSIColors',
    'format_file_size',
    'open_file_in_default_app',
    '_format_error_msg',
    # Logging + performance
    'JSONFormatter',
    'setup_logging',
    'PerformanceTracker',
    # Config validation + credentials
    'ConfigValidator',
    'validate_config_file',
    'validate_credentials',
    'CredentialLoader',
    'CredentialResolver',
    'DotenvCredentialLoader',
    'EnvironmentCredentialLoader',
    'JsonFileCredentialLoader',
    'filter_credentials',
    'load_credentials_from_env',
    'normalize_credential_value',
    'validate_env_credentials',
    # Profiles
    'add_profile_interactive',
    'get_cja_home',
    'get_profile_path',
    'get_profiles_dir',
    'list_profiles',
    'load_profile_credentials',
    'resolve_active_profile',
    'show_profile',
    'test_profile',
    'validate_profile_name',
]


from cja_auto_sdr.core.lazy import make_getattr

__getattr__ = make_getattr(
    __name__,
    [
        "JSONFormatter",
        "setup_logging",
        "PerformanceTracker",
        "ConfigValidator",
        "validate_config_file",
        "validate_credentials",
        "CredentialLoader",
        "CredentialResolver",
        "DotenvCredentialLoader",
        "EnvironmentCredentialLoader",
        "JsonFileCredentialLoader",
        "filter_credentials",
        "load_credentials_from_env",
        "normalize_credential_value",
        "validate_env_credentials",
        "add_profile_interactive",
        "get_cja_home",
        "get_profile_path",
        "get_profiles_dir",
        "list_profiles",
        "load_profile_credentials",
        "resolve_active_profile",
        "show_profile",
        "test_profile",
        "validate_profile_name",
    ],
    mapping={
        "JSONFormatter": "cja_auto_sdr.core.logging",
        "setup_logging": "cja_auto_sdr.core.logging",
        "PerformanceTracker": "cja_auto_sdr.core.perf",
        "ConfigValidator": "cja_auto_sdr.core.config_validation",
        "validate_config_file": "cja_auto_sdr.core.config_validation",
        "validate_credentials": "cja_auto_sdr.core.config_validation",
        "CredentialLoader": "cja_auto_sdr.core.credentials",
        "CredentialResolver": "cja_auto_sdr.core.credentials",
        "DotenvCredentialLoader": "cja_auto_sdr.core.credentials",
        "EnvironmentCredentialLoader": "cja_auto_sdr.core.credentials",
        "JsonFileCredentialLoader": "cja_auto_sdr.core.credentials",
        "filter_credentials": "cja_auto_sdr.core.credentials",
        "load_credentials_from_env": "cja_auto_sdr.core.credentials",
        "normalize_credential_value": "cja_auto_sdr.core.credentials",
        "validate_env_credentials": "cja_auto_sdr.core.credentials",
        "add_profile_interactive": "cja_auto_sdr.core.profiles",
        "get_cja_home": "cja_auto_sdr.core.profiles",
        "get_profile_path": "cja_auto_sdr.core.profiles",
        "get_profiles_dir": "cja_auto_sdr.core.profiles",
        "list_profiles": "cja_auto_sdr.core.profiles",
        "load_profile_credentials": "cja_auto_sdr.core.profiles",
        "resolve_active_profile": "cja_auto_sdr.core.profiles",
        "show_profile": "cja_auto_sdr.core.profiles",
        "test_profile": "cja_auto_sdr.core.profiles",
        "validate_profile_name": "cja_auto_sdr.core.profiles",
    },
)
